/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bus_Reservation;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class cancel_ticket extends javax.swing.JFrame {

    /**
     * Creates new form cancel_ticket
     */
    public cancel_ticket() {
        initComponents();
        connect();
    }
    String username_ct;
    String gmail_ct;

    Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;
    ResultSet rs;
    public void connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/terminal","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(cancel_ticket.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(cancel_ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /*
    public void enable_submit()
    {
        try {
            pst=con.prepareStatement("Select comment from ticket_cancel where email=?");
            pst.setString(1,gmail_ct);
            rs=pst.executeQuery();
            while(rs.next())
            {
                String x=rs.getString(1);
                if(x.equals("Pending"))
                {
                    submit_ct.setEnabled(false);
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(cancel_ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        route_ct = new javax.swing.JComboBox<>();
        seats_ct = new javax.swing.JTextField();
        date_ct = new com.toedter.calendar.JDateChooser();
        time_ct = new javax.swing.JComboBox<>();
        submit_ct = new javax.swing.JButton();
        cancel_ct = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        seat_quantity = new javax.swing.JTextField();
        seats_ct1 = new javax.swing.JTextField();
        seats_ct3 = new javax.swing.JTextField();
        seats_ct2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        operator = new javax.swing.JComboBox<>();
        card_number = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Select Route:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Select Seats :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Select Date      ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Select Time      ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Select Informations and Submitted to the Authority for being approved");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        route_ct.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        route_ct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinajpur-Rangpur", "Dinajpur-Panchagarh", "Dinajpur-Bogra" }));

        seats_ct.setEditable(false);
        seats_ct.setBackground(new java.awt.Color(255, 255, 255));
        seats_ct.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        seats_ct.setForeground(new java.awt.Color(255, 255, 255));
        seats_ct.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        seats_ct.setBorder(null);

        time_ct.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        time_ct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9AM", "12PM", "3PM" }));

        submit_ct.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        submit_ct.setText("Submit");
        submit_ct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submit_ctMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submit_ctMouseExited(evt);
            }
        });
        submit_ct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_ctActionPerformed(evt);
            }
        });

        cancel_ct.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cancel_ct.setText("Cancel");
        cancel_ct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancel_ctMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancel_ctMouseExited(evt);
            }
        });
        cancel_ct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_ctActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.blue);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Number of seats to be cancelled:");

        seat_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                seat_quantityKeyReleased(evt);
            }
        });

        seats_ct1.setEditable(false);
        seats_ct1.setBackground(new java.awt.Color(255, 255, 255));
        seats_ct1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        seats_ct1.setForeground(new java.awt.Color(255, 255, 255));
        seats_ct1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        seats_ct1.setBorder(null);

        seats_ct3.setEditable(false);
        seats_ct3.setBackground(new java.awt.Color(255, 255, 255));
        seats_ct3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        seats_ct3.setForeground(new java.awt.Color(255, 255, 255));
        seats_ct3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        seats_ct3.setBorder(null);

        seats_ct2.setEditable(false);
        seats_ct2.setBackground(new java.awt.Color(255, 255, 255));
        seats_ct2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        seats_ct2.setForeground(new java.awt.Color(255, 255, 255));
        seats_ct2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        seats_ct2.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Mobile No        ");

        mobile.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("Operator           ");

        operator.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        operator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bkash", "Rocket", "Nagad", "Atm Card", "Master Card" }));

        card_number.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("Card Number   ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(584, 584, 584))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seat_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(route_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(seats_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(seats_ct1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(seats_ct2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(seats_ct3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(operator, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(date_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(157, 157, 157)
                                            .addComponent(time_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(submit_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cancel_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(card_number)))
                        .addContainerGap())))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(route_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seat_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seats_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seats_ct1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seats_ct2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seats_ct3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(submit_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(cancel_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operator, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card_number, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submit_ctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_ctActionPerformed
        try {
            // TODO add your handling code here:
            String route=route_ct.getSelectedItem().toString();
            String number=seat_quantity.getText();
            String key="";
            if(number.equals("1"))
            {
                key=seats_ct.getText();
            }
            else if(number.equals("2"))
            {
                key=seats_ct.getText()+","+seats_ct1.getText();
            }
            else if(number.equals("3"))
            {
                key=seats_ct.getText()+","+seats_ct1.getText()+","+seats_ct2.getText();
            }
            else if(number.equals("4"))
            {
                key=seats_ct.getText()+","+seats_ct1.getText()+","+seats_ct2.getText()+","+seats_ct3.getText();
            }
            SimpleDateFormat dt=new SimpleDateFormat("yyyy-MM-dd");
            String date=dt.format(date_ct.getDate());
            String time=time_ct.getSelectedItem().toString();
            String Mobile=mobile.getText();
            String cmnt="Pending";
            String op=operator.getSelectedItem().toString();
            String card=card_number.getText();
            
            if(route.isEmpty() || key.isEmpty() || date.isEmpty() || time.isEmpty() || Mobile.isEmpty() || card.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Invalid selection");
            }
            else
            {
                if(Mobile.length()==11)
                {
                    if(op.equals("Bkash") || op.equals("Rocket") || op.equals("Nagad"))
                    {
                        if(card.length()==11)
                        {
                            pst=con.prepareStatement("insert into ticket_cancel(user,email,busno,seat,date,time,mobile,operator,card_number)values(?,?,?,?,?,?,?,?,?)");
                            pst.setString(1,username_ct);
                            pst.setString(2,gmail_ct);
                            pst.setString(3,route);
                            pst.setString(4,key);
                            pst.setString(5,date);
                            pst.setString(6,time);
                            pst.setString(7, Mobile);
                            pst.setString(8,op);
                            pst.setString(9,card);
                            pst.executeUpdate();

                            JOptionPane.showMessageDialog(this,"Submitted Successfully,Please wait for the Approval");

                            pst1=con.prepareStatement("update account_comments set comments=? where email=?");
                            pst1.setString(1,"Your cancellation request for "+route+" Date :"+date+" Time:"+time+" is pending now");
                            pst1.setString(2, gmail_ct);
                            pst1.executeUpdate();


                            jLabel6.setText("Your request for cancelling tickets is pending now.");

                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this,"Invalid Card Number");
                        }  
                    }
                    else if(op.equals("Atm Card") || op.equals("Master Card"))
                    {
                        if(card.length()==16)
                        {
                            pst=con.prepareStatement("insert into ticket_cancel(user,email,busno,seat,date,time,mobile,operator,card_number)values(?,?,?,?,?,?,?,?,?)");
                            pst.setString(1,username_ct);
                            pst.setString(2,gmail_ct);
                            pst.setString(3,route);
                            pst.setString(4,key);
                            pst.setString(5,date);
                            pst.setString(6,time);
                            pst.setString(7, Mobile);
                            pst.setString(8,op);
                            pst.setString(9,card);
                            pst.executeUpdate();

                            JOptionPane.showMessageDialog(this,"Submitted Successfully,Please wait for the Approval");

                            pst1=con.prepareStatement("update account_comments set comments=? where email=?");
                            pst1.setString(1,"Your cancellation request for "+route+" Date :"+date+" Time:"+time+" is pending now");
                            pst1.setString(2, gmail_ct);
                            pst1.executeUpdate();


                            jLabel6.setText("Your request for cancelling tickets is pending now.");

                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this,"Invalid Card Number");
                        }  
                    }
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Check Mobile Number");
                }   
            } 
        } catch (SQLException ex) {
            Logger.getLogger(cancel_ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_submit_ctActionPerformed
   
    private void seat_quantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seat_quantityKeyReleased
        // TODO add your handling code here:
        String number=seat_quantity.getText();
        if(number.isEmpty())
        {
            
            seats_ct.setEditable(false);
            seats_ct.setBackground(Color.white);
            seats_ct.setText("");

            seats_ct1.setEditable(false);
            seats_ct1.setBackground(Color.white);
            seats_ct1.setText("");

            seats_ct2.setEditable(false);
            seats_ct2.setBackground(Color.white);
            seats_ct2.setText("");

            seats_ct3.setEditable(false);
            seats_ct3.setBackground(Color.white);
            seats_ct3.setText("");
        }
        else
        {

            if(number.equals("1"))
            {
                seats_ct.setEditable(true);
                seats_ct.setBackground(Color.BLUE);
                
            }
            else if(number.equals("2"))
            {
                seats_ct.setEditable(true);
                seats_ct.setBackground(Color.BLUE);
                seats_ct1.setEditable(true);
                seats_ct1.setBackground(Color.BLUE);
            }
            else if(number.equals("3"))
            {
                seats_ct.setEditable(true);
                seats_ct.setBackground(Color.BLUE);
                seats_ct1.setEditable(true);
                seats_ct1.setBackground(Color.BLUE);
                seats_ct2.setEditable(true);
                seats_ct2.setBackground(Color.BLUE);
            }
            else if(number.equals("4"))
            {
                seats_ct.setEditable(true);
                seats_ct.setBackground(Color.BLUE);
                seats_ct1.setEditable(true);
                seats_ct1.setBackground(Color.BLUE);
                seats_ct2.setEditable(true);
                seats_ct2.setBackground(Color.BLUE);
                seats_ct3.setEditable(true);
                seats_ct3.setBackground(Color.BLUE);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Invalid Seat Numbers");
                seat_quantity.setText("");
                
                seats_ct.setEditable(false);
                seats_ct.setBackground(Color.white);
                seats_ct1.setEditable(false);
                seats_ct1.setBackground(Color.white);
                seats_ct2.setEditable(false);
                seats_ct2.setBackground(Color.white);
                seats_ct3.setEditable(false);
                seats_ct3.setBackground(Color.white);
            }
        }
          
    }//GEN-LAST:event_seat_quantityKeyReleased

    private void cancel_ctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_ctActionPerformed
        // TODO add your handling code here:
        dashboard db=new dashboard();
        db.setVisible(true);
        db.set_intro(username_ct,gmail_ct);
        db.username.setText(username_ct);
        db.email.setText(gmail_ct);
        this.setVisible(false);
    }//GEN-LAST:event_cancel_ctActionPerformed

    private void submit_ctMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_ctMouseEntered
        // TODO add your handling code here:
        submit_ct.setForeground(Color.BLUE);
    }//GEN-LAST:event_submit_ctMouseEntered

    private void submit_ctMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_ctMouseExited
        // TODO add your handling code here:
        submit_ct.setForeground(Color.BLACK);
    }//GEN-LAST:event_submit_ctMouseExited

    private void cancel_ctMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_ctMouseEntered
        // TODO add your handling code here:
        cancel_ct.setForeground(Color.BLUE);
    }//GEN-LAST:event_cancel_ctMouseEntered

    private void cancel_ctMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_ctMouseExited
        // TODO add your handling code here:
        cancel_ct.setForeground(Color.BLACK);
    }//GEN-LAST:event_cancel_ctMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cancel_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cancel_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cancel_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cancel_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cancel_ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_ct;
    private javax.swing.JTextField card_number;
    private com.toedter.calendar.JDateChooser date_ct;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobile;
    private javax.swing.JComboBox<String> operator;
    private javax.swing.JComboBox<String> route_ct;
    private javax.swing.JTextField seat_quantity;
    private javax.swing.JTextField seats_ct;
    private javax.swing.JTextField seats_ct1;
    private javax.swing.JTextField seats_ct2;
    private javax.swing.JTextField seats_ct3;
    private javax.swing.JButton submit_ct;
    private javax.swing.JComboBox<String> time_ct;
    // End of variables declaration//GEN-END:variables
}
