/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bus_Reservation;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        connect();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public void connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/terminal","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    public void set_intro(String Username_DB,String Email_DB)
    {
        username.setText(Username_DB);
        email.setText(Email_DB);
        
        String x="";
        try {
            pst=con.prepareStatement("select comments from account_comments where email=?");
            pst.setString(1,Email_DB);
            rs=pst.executeQuery();
            while(rs.next())
            {
                x=rs.getString(1);
            }
            comment.setText(x);
        } catch (SQLException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    public void receiptname()
    {
        download_receipt dr=new download_receipt();
        dr.setVisible(true);
        dr.receipt_label2.setText(username.getText()+"`s"+" Receipts");
        dr.load(email.getText());
        dr.username_DR=username.getText();
        dr.gmail_DR=email.getText();
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        personal_info = new javax.swing.JLabel();
        ticket_booking = new javax.swing.JLabel();
        Ticket_cancelling = new javax.swing.JLabel();
        downld_receipt = new javax.swing.JLabel();
        acc_deletion = new javax.swing.JLabel();
        chng_passwrd = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        comment = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Welcome To Your Profile");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        personal_info.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        personal_info.setText("   Personal Information");
        personal_info.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        personal_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personal_infoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                personal_infoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                personal_infoMouseExited(evt);
            }
        });

        ticket_booking.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        ticket_booking.setText("        Ticket Booking");
        ticket_booking.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ticket_booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticket_bookingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ticket_bookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ticket_bookingMouseExited(evt);
            }
        });

        Ticket_cancelling.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Ticket_cancelling.setText("    Ticket Cancellation");
        Ticket_cancelling.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ticket_cancelling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ticket_cancellingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ticket_cancellingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ticket_cancellingMouseExited(evt);
            }
        });

        downld_receipt.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        downld_receipt.setText("     Download Receipt");
        downld_receipt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        downld_receipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downld_receiptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                downld_receiptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                downld_receiptMouseExited(evt);
            }
        });

        acc_deletion.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        acc_deletion.setText("     Account Deletion");
        acc_deletion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        acc_deletion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acc_deletionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                acc_deletionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                acc_deletionMouseExited(evt);
            }
        });

        chng_passwrd.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        chng_passwrd.setText("     Change Password");
        chng_passwrd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chng_passwrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chng_passwrdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chng_passwrdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chng_passwrdMouseExited(evt);
            }
        });

        logout.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        logout.setText("             Log Out");
        logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        username.setEditable(false);
        username.setBackground(new java.awt.Color(204, 204, 255));
        username.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        username.setBorder(null);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("G:\\Level_3,1\\Software Project\\pics\\hello.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Account Activities");

        email.setEditable(false);
        email.setBackground(new java.awt.Color(204, 204, 255));
        email.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        email.setBorder(null);

        comment.setEditable(false);
        comment.setBackground(new java.awt.Color(204, 204, 255));
        comment.setColumns(20);
        comment.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        comment.setRows(5);
        comment.setBorder(null);
        jScrollPane1.setViewportView(comment);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(email))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Ticket_cancelling, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ticket_booking, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(personal_info, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(acc_deletion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(downld_receipt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chng_passwrd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(personal_info, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ticket_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ticket_cancelling, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(downld_receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acc_deletion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chng_passwrd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logout))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        Bus_Reservation BR=new Bus_Reservation();
        BR.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setForeground(Color.BLUE);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setForeground(Color.BLACK);
    }//GEN-LAST:event_logoutMouseExited

    private void personal_infoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personal_infoMouseEntered
        // TODO add your handling code here:
        personal_info.setForeground(Color.BLUE);
    }//GEN-LAST:event_personal_infoMouseEntered

    private void personal_infoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personal_infoMouseExited
        // TODO add your handling code here:
       personal_info.setForeground(Color.BLACK);
    }//GEN-LAST:event_personal_infoMouseExited

    private void ticket_bookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket_bookingMouseEntered
        // TODO add your handling code here:
        ticket_booking.setForeground(Color.BLUE);
    }//GEN-LAST:event_ticket_bookingMouseEntered

    private void ticket_bookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket_bookingMouseExited
        // TODO add your handling code here:
        ticket_booking.setForeground(Color.BLACK);
    }//GEN-LAST:event_ticket_bookingMouseExited

    private void Ticket_cancellingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ticket_cancellingMouseEntered
        // TODO add your handling code here:
        Ticket_cancelling.setForeground(Color.BLUE);
    }//GEN-LAST:event_Ticket_cancellingMouseEntered

    private void Ticket_cancellingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ticket_cancellingMouseExited
        // TODO add your handling code here:
        Ticket_cancelling.setForeground(Color.BLACK);
    }//GEN-LAST:event_Ticket_cancellingMouseExited

    private void downld_receiptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downld_receiptMouseEntered
        // TODO add your handling code here:
        downld_receipt.setForeground(Color.BLUE);
    }//GEN-LAST:event_downld_receiptMouseEntered

    private void downld_receiptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downld_receiptMouseExited
        // TODO add your handling code here:
        downld_receipt.setForeground(Color.BLACK);
    }//GEN-LAST:event_downld_receiptMouseExited

    private void acc_deletionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_deletionMouseEntered
        // TODO add your handling code here:
        acc_deletion.setForeground(Color.BLUE);
    }//GEN-LAST:event_acc_deletionMouseEntered

    private void acc_deletionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_deletionMouseExited
        // TODO add your handling code here:
        acc_deletion.setForeground(Color.BLACK);
    }//GEN-LAST:event_acc_deletionMouseExited

    private void chng_passwrdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chng_passwrdMouseEntered
        // TODO add your handling code here:
        chng_passwrd.setForeground(Color.BLUE);
    }//GEN-LAST:event_chng_passwrdMouseEntered

    private void chng_passwrdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chng_passwrdMouseExited
        // TODO add your handling code here:
        chng_passwrd.setForeground(Color.BLACK);
    }//GEN-LAST:event_chng_passwrdMouseExited

    private void ticket_bookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket_bookingMouseClicked
        // TODO add your handling code here:
        Customer_choice choice=new Customer_choice();
        choice.setVisible(true);
        choice.gmail_cch=email.getText();
        choice.username_cch=username.getText();
        this.setVisible(false);
    }//GEN-LAST:event_ticket_bookingMouseClicked

    private void downld_receiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downld_receiptMouseClicked
        // TODO add your handling code here:
        receiptname();
        
        
    }//GEN-LAST:event_downld_receiptMouseClicked

    private void Ticket_cancellingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ticket_cancellingMouseClicked
        // TODO add your handling code here:
        cancel_ticket ct=new cancel_ticket();
        ct.username_ct=username.getText();
        ct.gmail_ct=email.getText();
        //ct.enable_submit();
        ct.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Ticket_cancellingMouseClicked

    private void personal_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personal_infoMouseClicked
        // TODO add your handling code here:
        personal_info pi=new personal_info();
        pi.username_pi=username.getText();
        pi.gmail_pi=email.getText();
        pi.setVisible(true);
        pi.setheader();
        pi.setinformations();
        this.setVisible(false);   
    }//GEN-LAST:event_personal_infoMouseClicked

    private void chng_passwrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chng_passwrdMouseClicked
        // TODO add your handling code here:
        change_password cp=new change_password();
        cp.username_cp=username.getText();
        cp.gmail_cp=email.getText();
        cp.send_otp();
        cp.setVisible(true);
        cp.password();
        this.setVisible(false);
    }//GEN-LAST:event_chng_passwrdMouseClicked

    private void acc_deletionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_deletionMouseClicked
        // TODO add your handling code here:
        account_deletion ad=new account_deletion();
        ad.username_ad=username.getText();
        ad.gmail_ad=email.getText();
        ad.getpass();
        ad.mobileno();
        ad.setVisible(true);
        this.setVisible(false); 
        
    }//GEN-LAST:event_acc_deletionMouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ticket_cancelling;
    private javax.swing.JLabel acc_deletion;
    private javax.swing.JLabel chng_passwrd;
    public javax.swing.JTextArea comment;
    private javax.swing.JLabel downld_receipt;
    public javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel personal_info;
    private javax.swing.JLabel ticket_booking;
    public javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
